### ISSUE TITLE
Could you extract the MondialRelay API ? 

### ISSUE THREAD

**Issue by lyrixx** [sherlockode/SyliusMondialRelayPlugin#63]
Hello,

I want to use the MondialRelay API on my website, but I don't use sylius.
Could you extract the library into a standalone package?

Thanks

**Comment by NeilPeyssard** [comment]
Hello,

Extracting the Mondial Relay library from the plugin to a standalone package is not planned, but you can use another package for this, like [quentinbontemps/php-mondialrelay-api](https://packagist.org/packages/quentinbontemps/) for example.

**Comment by lyrixx** [comment]
okay, thanks. [quentinbontemps/php-mondialrelay-api](https://packagist.org/packages/quentinbontemps/)seems quite abandoned, that's why I chose your lib.

**Comment by lyrixx** [comment]
I'm closing this issue, as explained in this [comment](https://github.com/sherlockode/SyliusMondialRelayPlugin/issues/63#issuecomment-1778666975)
